[package]
edition = "2024"
name = "zmanim-core"
version = "0.1.0"

[dependencies]
libm = "0.2.15"

[dependencies.chrono]
version = "0.4.41"
default-features = false

[dev-dependencies]
j4rs = "0.22.0"
rand = "0.9.2"
serde_json = "1.0"

[dev-dependencies.serde]
version = "1.0"
features = ["derive"]

[workspace]
members = [
    "zmanim-card",
    # "zmanim_card",
]
resolver = "3"
