[package]
name = "zmanim-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", default-features = false }
libm = "0.2.15"

[dev-dependencies]
rand = "0.9.2"
j4rs = "0.22.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
