[package]
name = "zmanim-core"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
chrono = { version = "0.4.41", default-features = false }
rust_decimal = { version = "1.37.2", default-features = false }

[dev-dependencies]
j4rs = "0.22.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
