name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run tests
        run: RUSTFLAGS="-A warnings" cargo test

      - name: Run tests with uniffi feature
        run: RUSTFLAGS="-A warnings" cargo test --features="uniffi"
  bindgen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build Crate
        run: cargo build --release --features="uniffi"

      # Runs to ensure that our uniffi-bindgen is working.
      # This package does not provide bindings for all languages, so we need to run it to ensure that it is working.
      - name: Run python bindgen
        working-directory: uniffi-bindgen
        run: cargo run --bin uniffi-bindgen generate --library ../target/release/libzmanim_core.so --language python --out-dir pythonout
